### ISSUE TITLE
Logo Proposal for mota

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [Houfeng/mota#10]
Hello,
This my logo/Icon design for your project. It's free for your project.

I design this logo using adobe illustrator cc 2018. I hope you like this logo.

![mota-01](https://user-images.githubusercontent.com/35112507/39087728-30e47c0e-45c7-11e8-9128-4369da7f204b.jpg)

If you need anything change please contact me

Md Nazmul Hasan
Email : nazmul.hasan27771@gmail.com

Thank You.

**Comment by Houfeng** [comment]
thx
