### ISSUE TITLE
Is it just like mbox?

### ISSUE THREAD

**Issue by horizon0514** [Houfeng/mota#11]
RT

**Comment by Houfeng** [comment]
通过 RT 判断应该是认得中文的 ;-D

和 mbox 有相似之处，但又不同，mota 仅有很少的 api，mota 期望在编写模型之前，先放下 React 也放下 mota，就用单纯的 JavaScript 去编写你的业务模型，或有一个或多个类、或就是几个 Object，依它们应有的、自然的关系去抽像就行了，业务模型不依赖于 UI、也不依赖于某个框架，它易于测试，你可以针对它做单元测试。它易于重用，你可以将它用在合适的地方。最后， mota 只是出场把它关联到 react。

另外，mota 还给 react 带来的 mvvm 的特性，具备双向绑定的能力。

**Comment by 2724635499** [comment]
我也感觉和mobx差不多
