### ISSUE TITLE
mac下存在输入法乱跳的问题

### ISSUE THREAD

**Issue by xshong2008** [Houfeng/mota#5]
mac下，编辑到款出现编辑器滚动条是，当光标出现在文档中间，搜狗输入法在快速输入词语的时候，输入法光标会乱跳到文档的最末尾去，此时在原光标的位置为拼音输入的情况，文档最末尾为需要输入的文字，其他输入法貌似也存在同样的情况（mac自带输入法）

**Comment by adrian-wang** [comment]
+1
