### ISSUE TITLE
mac下冷启动打开任意有内容的md文件，显示为空文件

### ISSUE THREAD

**Issue by woshihuangshuai** [Houfeng/mota#7]
mac下冷启动打开任意有内容的md文件，显示为空文件，关闭文件（不杀进程），再次打开文件，显示内容

**Comment by Houfeng** [comment]
能否提供？
1. mac os 版本
2. mditor 版本

**Comment by woshihuangshuai** [comment]
macOS: Sierra 10.12.5
mditor: 1.0.0
