### ISSUE TITLE
Mditor will crash when file is big. 

### ISSUE THREAD

**Issue by iascchen** [Houfeng/mota#8]
MAC OSX 10.12.5, mditor: 1.0.0
If file is big, press delete key in keyboard when editing, mditor will crash.
the file size is only 11kB
一般在文章的后半段出现这个现象。

**Comment by Houfeng** [comment]
@iascchen 
最后公司很忙，一直没有处理，有空了，一定加紧处理下

**Comment by iascchen** [comment]
其他功能都挺好用的，👍
