### ISSUE TITLE
请问这个怎么换别的框架，比如vue

### ISSUE THREAD

**Issue by Tindtily** [Houfeng/mota#9]
请问这个怎么换别的框架，比如vue

**Comment by Houfeng** [comment]
在用 mota 了吗？想在 vue 中使用 mota? mota 是在 react 下使用的库

**Comment by Tindtily** [comment]
没有，我只是看了简述，然后想到的。

>但是「业务模型」应该是没有过多依赖，应该是无关框架的，它应该随时可以被用在任何合适的 JavaScript 环境中，使用 mota 你可以用原生的普通的 JavaScript 代码编写你的「业务模型」，并让你的「业务模型」在不同框架、不同运行环境下重用更为容易。

**Comment by Houfeng** [comment]
嗯，独立的业务模型，不依赖 mota，是可以用于 vue 或其它框架，

**Comment by Tindtily** [comment]
能举个例子或者给个链接、关键词啥的吗？不太理解业务模型

**Comment by Houfeng** [comment]
这有一个 TodoList 的示例应用
- 在线示例 [http://houfeng.net/dn-template-mota/example/](http://houfeng.net/dn-template-mota/example/)
- 示例源码 [https://github.com/Houfeng/dn-template-mota](https://github.com/Houfeng/dn-template-mota)

**Comment by Tindtily** [comment]
Models目录下的TodoList.js和TodoItem.js就是业务模型吧
